### ISSUE TITLE
But did you try the code? First, there are problems on data. When you execute the conversion of X_train, two variable ("HandsetPrice" and "MaritalStatus") have values that are not numeric, and raise errors in conversion. I managed to eliminate those values. Then, there is no "Get metrics" section. Finally, the dataframe  "exp_df" does not exist

### ISSUE THREAD

**Issue by barcaroli** [JavierMtz5/ArtificialIntelligence#1]

**Comment by JavierMtz5** [comment]
Hi barcaroli, thank you for your review! I have executed the notebook and you are right, the bugs you reported need to be fixed!

I tried to clean the code from mi local work and make it more easy to follow, and it looks that I forgot/changed something... Sorry for that!

I will fix the code as soon as I can!
